apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  annotations:
    # sealed-secrets controller has to be synced before everything else
    # therefore we use -2
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.destinationServer }}
  project: default
  source:
    chart: sealed-secrets
    helm:
      values: |
        commandArgs:
          - --update-status
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
