# This sample SealedSecret contains the Secret below
# (note that it is sealed with MY certificate, you have to seal with yours)
###################################################
# apiVersion: v1
# kind: Secret
# metadata:
#   name: helm-values
#   namespace: argocd
# stringData:
#   grafana-values.yaml: |
#     adminPassword: sEcReTPW$!_
#   postgresql-values.yaml: |
#     postgresqlPassword: SeCrEtPassword!
###################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helm-values
  namespace: argocd
  annotations:
    # This secret has to be synced after sealed-secrets controller but before the apps
    # therefore we set the sync-wave to -1
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    grafana-values.yaml: AgAl85i+wVfizWJNuzxTSozMxdn/akFhNFbtDD4Fb2i/eIZefb6S/Vx8P70vFIPTOAhYmaO4Mr0zcvCQTdv7C3oHf1PMXmSRV5MD5cxhqYqVw0TQVxau7arUjSzHxeiCC6pU/47Ugw9BEK3Q7Hw1K49cEdvLVp2x6dAirp/Gxty0IVTY5tdvsH4Q5vH6DrTVo2JT9WotDXikH6CDcGM266a/VUpufzuHYGQttE8mBLc03N0OqZicHMW7BPcbeHc55lj1nP9d2hKdy37YbQvM2xm3okXuozR/i/RRna5WkiAMjC6wjPr+l67pGjrqnzHFlHhVkz/fBPS8OaCwjnttY1fObRGOcISoEUlz56Iz0vZpSjqaxyhLD8F2ss4DCq2ctbjF7TAWHy6iCnEbeya6ARGga0dutMK0rApYQDYmj/22pImRoO87PyH+xP7f7/4C9tki3a5qaB14hNb3d1b+CaTUF3exOGWiteZjVw/qBvGIdVlKE11aHqb8CnFeJw+df93dgD7T3UcC3u9FZ380ppA2Nkcg3seusR6dT7fr6DH/XL3KcPZlg1L8Zmm2+mrikAjB2m7T0s4r3tmcvtXSPI96GxetXx95JRTrDHd1xVeNUyJO7ioK51PcCbKfqX1tWgYg+pMY+WQbT9txESc0pgaXWKOHEHOCAfLIB8R/c6da+VKK9TGkp0Hh1TZ9rwXhJJCt7iAbMsB34TzYOVIsPuG/IuVz1sTjB5E=
    postgresql-values.yaml: AgBrbLHdL2Y9AM6Ntd5P48Jo4bGwwBHuPIFy+PR31lXwWQrq57Tg4q5o66OtIHWuShyJsiOPmMIqPBMtDuOvptkqOsS81Mxl7VhNk2WuIqlf9XlR1D7b2eMBkuAnUVVX4EKUWZEx9xdw/6yYTTY0q01fPdNt3q5KLgwHxh71lbxfBsFr81ip/aBVyUoXgwWmL7gacPzVQQD5+A9fCDAVFmPiY6f2IBSUW3gqsgd8T235SAv66BYudoyHbhHU5FoA69XPGBN7f7y6ISwSpcQY0WZdedMqEPfV5u5UNdncY//ASIlJe4SlxsFiPgCpuE0sxq3CuWHZ0HtYjSeg5uf7l6QQfQreWmXRAh6XBbZuCxNi8xA/8FVE7SZbH+jX2Pdd9GBmFcar0qIL/6Ng/pFI2t736VD9QKmQ8TTPjhh0PHU+25FllixrTsn/GOYbCNJKT59kCpJ3iJmKS8HmcCwIaBStFDTHZzqROS+LlwT+CoAyLlhXux1/HTidizmH5BfKmLwtl7WXH8J7DZjcpoZHTl9echa8FcIag82WiDgbm7xjddpsyXYZSE5oVwpNpVFAYeB4uOwFiKdTQokfy+AFMqtum7Ejj4Ub6fJ+kotEU1Holo2ezd5jVMYgHY+KzfotLO+bXCPqlrdZJthrQKslmqpee7WqN7fZTjXBZEDtM39xR1gDAWs9qlA/bmLQAThRpqYQxUfdd5wjmo4v+lfGDxIBDRsJ2uleuaXCciPePm0=
  template:
    metadata:
      name: helm-values
      namespace: argocd
