apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    server: {{ .Values.destinationServer }}
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 10.9.4
    helm:
      # secret values will be sourced from the mounted secret into the argocd repo-server
      valueFiles:
        - /helm-values/postgresql.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
